######################################################################
# Automatically generated by qmake (2.01a) Fri May 4 00:26:58 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
